export let defaultSetting = {
    debugger:true,
    x:117.38984,
    y:39.14688,
    level:9,
    dynamicLayers:[

    ],
    geojson:[
        {
            id:'drowplane1Layer',
            paths:[[117.29,39.23],[117.34,39.12],[117.77,39.32]],
            fillColor:[255,33,22,0.3],//背景颜色
            lineWidth:1,//边界宽度
            lineColor:[0,0,0,1]//边界颜色
        }
    ],
    baseMap:{
        visibility:true,
        type:'tdt',//谷歌地图:google,天地图:tdt
        defaultshow:'layers',//影像图:imagesLayer,地形图:terrains,矢量图:layers
        labelLayerVisibility:true,//地图标注
        shadeLayer:{
            visibility:false,
            backgroundColor:'#fff',
            opacity:0.5
        }
    },
    search:{
        dynamicLayer:{
            'DLbackalllayer':{
                layerids:[0,1,2,3,4,5,6,7,9,10],
                ParamsDes:{
                    2:{
                        'NAME':'名称',
                        'Shape':'',
                        'GB':'',
                        'ANGLE':'',
                        'ORIG_FID':''
                    }
                },
                textSearchParams:['NAME','Shape','GB','ANGLE','ORIG_FID']
            },
            'NHBackalllayer':{
                layerids:[0,1,2,3,4,5,6,7,9,10],
                ParamsDes:{
                    3:{
                        'FID':'名称',
                        'Shape':'形状',
                        'GB':'容量',
                        'ANGLE':'面积',
                        'ORIG_FID':'起点'
                    }
                },
                textSearchParams:['NAME','Shape','GB','ANGLE','ORIG_FID']
            }
        }
    }

};
