import {xd,xx,zg} from './geoJSON';
export let defaultSetting = {
    debugger:true,
    x:117.38984,
    y:39.14688,
    level:6,
    baseMap:{
        visibility:true,
        type:'tdt',//谷歌地图:google,天地图:tdt
        defaultshow:'terrains',//影像图:images,地形图:terrains,矢量图:layers
        labelLayerVisibility:true,//地图标注
        shadeLayer:{
            visibility:true,
            opacity:0.5
        }
    },
    /** 动态图层 */
    dynamicLayers:[
        {
            name:'静海图层',
            id:'DLbackalllayer',
            url:'http://111.30.103.114:6080/arcgis/rest/services/DongLiMapFlood/MapServer',
            show:[0],//默认显示 ,1,2,3,4,5,6,7,9,10
            layers:{//图例显示对于名称
                0:'险工',
                1:'险段',
                2:'一级河道',
                3:'二级河道',
                4:'乡镇边界',
                5:'乡镇面',
                6:'水库',
                7:'支干渠',
                8:'地图遮罩 ',
                9:'市属二级河道',
                10:'区界外河流'
            },
            search:{//查询组件使用
                layerids:[3,4,5],//查询图层
                ParamsDes:{//对象描述
                    2:{
                        'NAME':'名称',
                        'Shape':'',
                        'GB':'',
                        'ANGLE':'',
                        'ORIG_FID':''
                    }
                },
                textSearchParams:['NAME','Shape','GB','ANGLE','ORIG_FID']
            },
            visibility:true
        },
        {
            name:'东丽图层',
            id:'NHBackalllayer',
            url:'http://111.30.97.35:8099/arcgis/rest/services/NHMAP/MapServer',
            show:[0],//,1,2,3,4,5,6,7,8
            layers:{
                0:'二级河道new',
                1:'一级河道',
                2:'外洪威胁村落',
                3:'企业',
                4:'边界',
                5:'乡镇 ',
                6:'水库',
                7:'西七里海',
                8:'盛庄洼 '
            },
            search:{
                layerids:[0,1,2,3,4,5,6,7,9,10],
                ParamsDes:{
                    3:{
                        'FID':'名称',
                        'Shape':'形状',
                        'GB':'容量',
                        'ANGLE':'面积',
                        'ORIG_FID':'起点'
                    }
                },
                textSearchParams:['NAME','Shape','GB','ANGLE','ORIG_FID']
            },
            visibility:true
        }
    ],
    /** geojson 图层 */
    geojson:[
        {
            id:'drowplane1Layer',
            geoJSON:zg,
            fillColor:[255,33,22,0],//背景颜色
            lineWidth:4,//边界宽度
            lineColor:[255,33,0,0.5],//边界颜色
            visibility:true
        },
        {
            id:'drowplane2Layer',
            geoJSON:xx,
            fillColor:[255,33,22,0.3],//背景颜色
            lineWidth:2,//边界宽度
            lineColor:[255,33,0,0.5],//边界颜色
            visibility:true
        }
    ],
    lend:{
        shadeLayerVisibility:false,
        labelsLayerVisibility:false
    },
    type:{
        dynamicLayers:{
        }
    },
    defaultMapState:'rainState',
    mapStateList:[
        {
            station:['rain'],
            dynamicLayers:{
                'DLbackalllayer':{
                    show:[0,1,2,3,4,5,6,7,9,10],
                    visibility:true
                },
                'NHBackalllayer':{
                    show:[0,1,2,3,4,5,6,7,8],
                    visibility:true
                }
            },
            baseMap:'images',
            geojson:['drowplane2Layer'],
            name:'雨情监测',
            id:'rainState'
        },
        {
            station:['water'],
            dynamicLayers:{
                'NHBackalllayer':{
                    show:[]
                }
            },
            geojson:['drowplane1Layer'],
            baseMap:'terrains',
            name:'水情监测',
            id:'waterState'
        }
    ]
};

